<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>ML and DL</b></center>

<center><b><h1>Lab - 6</b></center>    
<pre>    

# Decision Tree Classifier

In [1]:
from sklearn.datasets import load_iris 

# Import iris data ser using sklearn

In [10]:
data = load_iris()


In [9]:

data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

# Importing the libraries

In [22]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree

# Divide the data into input and output

In [15]:
X = data['data']
y = data['target']
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# Splitting the dataset into the Training set and Test set

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=43, stratify=y)

In [17]:
print(X_train.shape)

(120, 4)


In [18]:
print(X_test.shape)

(30, 4)


# Fitting DecisionTreeClassifier   on dataset

In [19]:
model = DecisionTreeClassifier(            
    random_state=42,
)


In [20]:
model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

# Display Decision Tree

In [23]:
%matplotlib qt

In [28]:
tree.plot_tree(model)

[Text(0.5416666666666666, 0.9285714285714286, 'x[2] <= 2.45\ngini = 0.667\nsamples = 120\nvalue = [40, 40, 40]'),
 Text(0.4583333333333333, 0.7857142857142857, 'gini = 0.0\nsamples = 40\nvalue = [40, 0, 0]'),
 Text(0.5, 0.8571428571428572, 'True  '),
 Text(0.625, 0.7857142857142857, 'x[3] <= 1.75\ngini = 0.5\nsamples = 80\nvalue = [0, 40, 40]'),
 Text(0.5833333333333333, 0.8571428571428572, '  False'),
 Text(0.4166666666666667, 0.6428571428571429, 'x[2] <= 5.35\ngini = 0.169\nsamples = 43\nvalue = [0, 39, 4]'),
 Text(0.3333333333333333, 0.5, 'x[0] <= 4.95\ngini = 0.093\nsamples = 41\nvalue = [0, 39, 2]'),
 Text(0.16666666666666666, 0.35714285714285715, 'x[1] <= 2.45\ngini = 0.5\nsamples = 2\nvalue = [0, 1, 1]'),
 Text(0.08333333333333333, 0.21428571428571427, 'gini = 0.0\nsamples = 1\nvalue = [0, 1, 0]'),
 Text(0.25, 0.21428571428571427, 'gini = 0.0\nsamples = 1\nvalue = [0, 0, 1]'),
 Text(0.5, 0.35714285714285715, 'x[2] <= 4.95\ngini = 0.05\nsamples = 39\nvalue = [0, 38, 1]'),
 Text(0

[Text(0.5486111111111112, 0.9285714285714286, 'X[1] <= 3.283\ngini = 0.665\nsamples = 105\nvalue = [38, 34, 33]'),
 Text(0.2638888888888889, 0.7857142857142857, 'X[3] <= 1.136\ngini = 0.634\nsamples = 73\nvalue = [14, 32, 27]'),
 Text(0.1111111111111111, 0.6428571428571429, 'X[3] <= 0.524\ngini = 0.476\nsamples = 23\nvalue = [14, 9, 0]'),
 Text(0.05555555555555555, 0.5, 'gini = 0.0\nsamples = 14\nvalue = [14, 0, 0]'),
 Text(0.16666666666666666, 0.5, 'gini = 0.0\nsamples = 9\nvalue = [0, 9, 0]'),
 Text(0.4166666666666667, 0.6428571428571429, 'X[3] <= 1.463\ngini = 0.497\nsamples = 50\nvalue = [0, 23, 27]'),
 Text(0.2777777777777778, 0.5, 'X[2] <= 5.315\ngini = 0.117\nsamples = 16\nvalue = [0, 15, 1]'),
 Text(0.2222222222222222, 0.35714285714285715, 'gini = 0.0\nsamples = 15\nvalue = [0, 15, 0]'),
 Text(0.3333333333333333, 0.35714285714285715, 'gini = 0.0\nsamples = 1\nvalue = [0, 0, 1]'),
 Text(0.5555555555555556, 0.5, 'X[3] <= 1.628\ngini = 0.36\nsamples = 34\nvalue = [0, 8, 26]'),
 Te

# Predict the x_test 

In [24]:
model.predict(X_test)

array([1, 0, 1, 1, 1, 2, 2, 0, 1, 2, 0, 1, 0, 0, 0, 1, 2, 1, 0, 1, 1, 0,
       2, 2, 2, 0, 2, 2, 0, 1])

In [25]:
y_test

array([1, 0, 2, 1, 1, 2, 2, 0, 1, 2, 0, 1, 0, 0, 0, 1, 2, 1, 0, 1, 1, 0,
       2, 2, 2, 0, 2, 2, 0, 1])

In [26]:
model.score(X_train,y_train)

1.0

In [27]:
model.score(X_test,y_test)

0.9666666666666667

# Import diabetes.csv dataset 

In [40]:
df = pd.read_csv('diabetes.csv')

In [41]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age       Outcome  
0                       0.627   50      Diabetic  
1                       0.351   31  Non Diabetic  
2                       0.672   32      Diabetic  
3                       0.167   21  Non Diabetic  
4                       2.288   33      Diabetic  
..                        ...  ...           ...  
763                     0.171   63  Non Diabetic  
764                     0.340   27  Non Diabetic  
765                     0.245   30  Non Diabetic  
766                     0.349   47      Diabetic  
767                     0.315   23  Non Diabetic  

[768 rows x 9 columns]

# Check the distribution of the target

In [42]:
df['Outcome'].value_counts()

Outcome
Non Diabetic    500
Diabetic        268
Name: count, dtype: int64

# Replace zeros with NaN for specific columns

In [44]:
copy_df = df.copy()
cols = ["Glucose","BloodPressure","SkinThickness","Insulin","BMI"]
copy_df[cols] = copy_df[cols].replace(0, np.nan)

# Check for missing values

In [45]:
print(copy_df.isnull().sum())

Pregnancies                   0
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64


# Fill missing values with median

In [47]:
copy_df['Glucose'].fillna(copy_df['Glucose'].mean(), inplace=True)
copy_df['BloodPressure'].fillna(copy_df['BloodPressure'].mean(), inplace=True)
copy_df['SkinThickness'].fillna(copy_df['SkinThickness'].median(), inplace=True)
copy_df['Insulin'].fillna(copy_df['Insulin'].median(), inplace=True)
copy_df['BMI'].fillna(copy_df['BMI'].median(), inplace=True)

C:\Users\meetj\AppData\Local\Temp\ipykernel_3304\3972210228.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  copy_df['Glucose'].fillna(copy_df['Glucose'].mean(), inplace=True)
C:\Users\meetj\AppData\Local\Temp\ipykernel_3304\3972210228.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as 

# Visualize Distributions

In [50]:
 import seaborn as sns
import matplotlib.pyplot as plt
sns.pairplot(copy_df, hue='Outcome')

In [52]:
plt.show()

# Convert Targer data into interger code

In [53]:
copy_df['Outcome'] = copy_df['Outcome'].str.strip()
copy_df['Outcome'] = copy_df['Outcome'].map({'Diabetic': 1, 'Non Diabetic': 0})

In [54]:
copy_df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6    148.0           72.0           35.0    125.0  33.6   
1              1     85.0           66.0           29.0    125.0  26.6   
2              8    183.0           64.0           29.0    125.0  23.3   
3              1     89.0           66.0           23.0     94.0  28.1   
4              0    137.0           40.0           35.0    168.0  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10    101.0           76.0           48.0    180.0  32.9   
764            2    122.0           70.0           27.0    125.0  36.8   
765            5    121.0           72.0           23.0    112.0  26.2   
766            1    126.0           60.0           29.0    125.0  30.1   
767            1     93.0           70.0           31.0    125.0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

# Divide the data into input and output

In [55]:
X = copy_df.drop('Outcome', axis=1)

In [56]:
y = copy_df['Outcome']

# Splitting the dataset into the Training set and Test set

In [57]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create Model

In [58]:
model = DecisionTreeClassifier(random_state=42)

# Fitting DecisionTreeClassifier   on dataset

In [59]:
model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

# Display Decision Tree

In [61]:
plt.figure(figsize=(20,10))
tree.plot_tree(model, filled=True, feature_names=X.columns, class_names=['Non Diabetic', 'Diabetic'])
plt.show()

# Predict the x_test 

In [62]:
y_pred = model.predict(X_test)

# Display Training Accuracy

In [63]:
print('Training Accuracy:', model.score(X_train, y_train))

Training Accuracy: 1.0


# Display Test Accuracy

In [64]:
print('Test Accuracy:', model.score(X_test, y_test))

Test Accuracy: 0.7207792207792207


# Confusion Matrix

In [65]:
cm = metrics.confusion_matrix(y_test, y_pred)

In [66]:
print(cm)

[[76 23]
 [20 35]]


In [67]:
plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.show()

# Save Model State

In [68]:
import pickle
filename = 'finalized_model.pkl'
pickle.dump(model, open(filename, 'wb'))

In [69]:
result = loaded_model.score(X_test, y_test)
print(result)

C:\Users\meetj\anaconda3\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  warnings.warn(


ValueError: X has 8 features, but DecisionTreeClassifier is expecting 4 features as input.

# Load Model from Disk

In [34]:
with open('model.pkl','rb') as file:
    loaded_model = pickle.load(file)

In [36]:
loaded_model.predict(X_test)

array([1, 0, 1, 1, 1, 2, 2, 0, 1, 2, 0, 1, 0, 0, 0, 1, 2, 1, 0, 1, 1, 0,
       2, 2, 2, 0, 2, 2, 0, 1])

In [38]:
from sklearn.metrics import classification_report
from sklearn import metrics

In [39]:
print(metrics.classification_report(y_test,y_predict))

NameError: name 'y_predict' is not defined